name: CI

on:
  workflow_dispatch:

  push:
    paths: [".cargo/**", "src/**", "tests/**", "Cargo.*", "CHANGELOG*"]
    branches: [main]

  pull_request:
    # https://github.com/orgs/community/discussions/25161#discussioncomment-3246673
    paths: [".cargo/**", "src/**", "tests/**", "Cargo.*", "CHANGELOG*"]
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  release_please:
    name: Release please
    if: ${{ !contains(github.event_name, 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust
          prerelease: true

  ci:
    name: Patrol
    needs: [release_please]
    if: ${{ !failure() && !cancelled() && !needs.release_please.outputs.created }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Prexec
        run: |
          ########## script ##########
          case "${{ matrix.os }}" in
            *'windows'*)
              echo "OPENSSL_SRC_PERL=C:/Strawberry/perl/bin/perl" | tee -a "$GITHUB_ENV"
              ;;
          esac
          cargo update

      - name: Run tests
        run: cargo test --all-features --workspace

      - name: Formatting check
        run: cargo fmt --all --check

      - name: Clippy check
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

